# Miedo II {-}


Tengo miedo<br>
de pretender ser lo que no soy.<br>
Miedo de arrepentirme,<br>
de maldecir aquella noche<br>
cuando te vi tan sola y tierna.<br>
De reprocharme eternamente<br>
por no haberte conocido anteriormente.

Miedo de convertirme<br>
en una anécdota más en tu vida<br>
que contarás a tus amigas.<br>
Miedo de no volver a ser el mismo,<br>
o peor aún, siendo yo mismo,<br>
al mismo tiempo ser un otro.

Me da miedo que me hagas sufrir,<br>
que se me rompa el corazón<br>
y que fragmentes mi memoria.<br>
Miedo de estar robándote tu tiempo<br>
de que malgastes tus momentos<br>
en este tonto que no puede<br>
por más que trate y que lo intente<br>
sacarte entera de su mente.<br>

Miedo de que en lugar de ser tu héroe<br>
sea tu demonio, tu villano.<br>
Tengo miedo de llorar,<br>
de salir desesperado<br>
a buscarte en todas partes<br>
como al que se le va vida en ello,<br>
por no lograr asimilar<br>
que mis "te amo", mis "te quiero"<br>
están a treinta grados bajo cero.

Miedo de que se evaporen mis deseos,<br>
de que se agoten mis latidos<br>
con mujeres que no quiera<br>
y malbarate mis anhelos,<br>
aunque entonces no me importe<br>
por ser trivial, ser lo de menos.

Miedo a perderte y que te vayas,<br>
de que te marches para siempre.<br>
Que te conviertas en tormenta<br>
y me conduzcas al naufragio.<br>
De que me llegues a hacer falta<br>
y de morir de sed de ti,

De sentirme vacío<br>
por no estar contigo.<br>
De que al leer este poema<br>
no sientas nada,<br>
si acaso lástima,<br>
no digas nada,<br>
tan sólo gracias.
