# Miedo I {-}


Miedo me da<br>
confesarte lo que siento.<br>
De que mi vida se defina<br>
antes de ti - después de ti.<br>
De que sigas inspirándome,<br>
retándome, importándome.

Miedo de que seas tú<br>
quien rediseñe mis esquemas,<br>
de convertirte en mi leyenda<br>
y que seas tú mi religión.<br>
De hacerle caso al corazón.

Tengo miedo de tus hadas,<br>
tus estrellas, tus manías;<br>
de tu sonrisa y de tu risa;<br>
de la forma en que acaricias<br>
tu cabello; cómo miras.<br>
Miedo a tu sol y de tu voz,<br>
miedo a tus "no sé"<br>
porque no sé qué significan.

Tengo demasiado miedo<br>
de llegar a perder la noción del tiempo,<br>
de que una hora contigo<br>
sea un minuto a tu lado<br>
y que un segundo sin verte<br>
se multiplique por dos, tres o cuatro.<br>
Que tu tristeza me entristezca<br>
y que me alegre tu alegría,<br>
tu seriedad me ponga serio<br>
y que tu muerte sea la mía.

De que el hablar con tu recuerdo<br>
sea la mejor manera que he encontrado<br>
de poder perder el tiempo<br>
sin sentir realmente que lo pierdo.<br>
De que un<br>
"no hace falta que vengas a verme"<br>
baste para salir corriendo a verte.<br>

De que seas parte de mi historia<br>
la principal protagonista,<br>
de que seas tú mi heroína.<br>
De que descubras en mi alma<br>
un ser oculto que te ama.<br>
De que seas tú mi certidumbre<br>
y que un abrazo tuyo sea<br>
lo que detenga mi derrumbe.<br>
De que tus labios y los míos<br>
se digan todo con un beso.<br>

Me da miedo que me enfermes<br>
y de tu nombre ser adicto.<br>
De entregarme y darlo todo<br>
de dar el ciento diez por ciento<br>
y no pedirte nada a cambio.<br>
De que seas lo mejor de mi vida.<br>
Miedo de ti, es cierto<br>
porque me estoy enamorando,<br>
porque me estás enamorando.
