# Perdón {-}


Con una vela entre tus manos<br>
rodilla al suelo, mirada triste<br>
te encuentras sola y moribunda<br>
rogando a un Dios que no te escucha<br>
sin hacer caso a tus plegarias<br>
al no entender lo que le pides.

Sin que lo notes ni lo sepas<br>
con el tañir de las campanas<br>
tu fe se agota y se evapora<br>
para mezclarse con incienso<br>
dejando espacio entre tu pecho<br>
a ese vacío insoportable.

Y de repente en un instante<br>
mientras se aprecia un Padre Nuestro<br>
entre tus labios sin hablar,<br>
la flama aviva, toma fuerza<br>
y aquella cera derretida<br>
entre tus dedos se desliza.

Te va quemando mas no sientes<br>
pues el dolor está ocupado<br>
en destrozar el corazón<br>
de ese Cristo enfrente tuyo<br>
que clava fija su mirada<br>
como queriendo ver tu alma.

Se acerca un cura y te pregunta<br>
con una Biblia entre sus manos<br>
-¿pasa algo malo hija mía?<br>
pero tus ojos no le miran,<br>
con una gran nudo en la garganta<br>
estás temblando, estás llorando.

Ya las campanas han callado<br>
Suspiras hondo, muerdes tus labios<br>
Ante el altar juras en vano<br>
Ya no hay lugar para el perdón.<br>
¿Perdonar? !Si el tiempo no pudo!<br>
Tú no lo harás... que lo haga Dios.
