# Quisiera {-}


Quisiera poder algún día<br>
decir que mi mundo eres tú<br>
Que te tiemble la voz<br>
mientras leas estas líneas.<br>
Que tu corazón se acelere<br>
que tu sangre se hiele<br>
y tus ojos se aneguen;<br>
sentir que te falta el aliento,<br>
que te ahogas por dentro.<br>

Pensar en ti cada día<br>
y echarte por siempre de menos.<br>
Saber que eres tú y nadie más;<br>
poder sentir algún día<br>
cómo al ver tu mirada<br>
se electrocuta mi alma;<br>
morirme de nervios<br>
al esperar tu llegada;<br>
que eres tú mi camino<br>
y también mi destino<br>
saber que contigo he ganado<br>
y poder decir<br>
que mi vida eres tú.

Quisiera decirte algún día<br>
que eres tú vida mía<br>
lo que más me haces falta.<br>
Que eres tú de repente<br>
la que siempre yo quise<br>
y saber finalmente,<br>
como acero en el frío,<br>
que tu ausencia este tiempo<br>
no fue invierno ni muerte,<br>
fue tan sólo un suspiro.

Quisiera besarte algún día<br>
sin que tú me lo pidas,<br>
sin que yo ni lo piense,<br>
sin que nada lo impida.<br>
Hasta entonces seré<br>
la persona que he sido:<br>
el que siempre quisiste,<br>
por quien tanto morías.
